services:
  - type: web
    name: autou-email-classifier
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: DEBUG
        value: false
      - key: CORS_ORIGINS
        value: "*"
